"""Internationalisation (EN / AR) for Car Service AI.

Arabic is the only translated language: for every other language the English
source string is used unchanged.  The ``t()`` helper is exposed to Jinja as a
global so templates can write ``{{ t('Dashboard') }}``.
"""
from __future__ import annotations

from typing import Any


# ---------------------------------------------------------------------------
# Arabic strings, keyed by the English source text.
# ---------------------------------------------------------------------------

AR: dict[str, str] = {
    # ---- app shell (base.html) ----
    "AI Mechanic": "ميكانيكي ذكي",
    "Main": "الرئيسية",
    "Dashboard": "لوحة التحكم",
    "AI Chat": "محادثة الذكاء الاصطناعي",
    "demo": "تجريبي",
    "Diagnose": "التشخيص",
    "By Text": "بالنص",
    "By Image": "بالصورة",
    "By Audio": "بالصوت",
    "Garage": "المرآب",
    "My Vehicle": "سيارتي",
    "Maintenance": "الصيانة",
    "Repair Guide": "دليل الإصلاح",
    "Insights": "التحليلات",
    "Reports": "التقارير",
    "System": "النظام",
    "Settings": "الإعدادات",
    "About": "حول",
    "Contact": "تواصل معنا",
    "Demo mode": "الوضع التجريبي",
    "Demo mode · ": "الوضع التجريبي · ",
    "add API key": "أضف مفتاح API",
    "Gemini online": "جيميني متصل",
    "AI System Online": "نظام الذكاء الاصطناعي متصل",
    "Guest": "زائر",
    "Toggle theme": "تبديل المظهر",
    "Menu": "القائمة",
    "Change language": "تغيير اللغة",
    "Search (Ctrl+K)": "بحث (Ctrl+K)",
    "Notifications": "الإشعارات",
    "Mark all read": "تحديد الكل كمقروء",
    "Diagnosis complete": "اكتمل التشخيص",
    "Engine analysis report is ready.": "تقرير تحليل المحرك جاهز.",
    "Maintenance due": "صيانة مستحقة",
    "Oil change due in 300 km.": "تغيير الزيت مستحق خلال 300 كم.",
    "Welcome aboard 🚗": "مرحباً بك 🚗",
    "Welcome aboard": "مرحباً بك",
    "Try the AI Chat or Diagnose by Image.": "جرّب محادثة الذكاء الاصطناعي أو التشخيص بالصورة.",
    "Account": "الحساب",
    "Log out": "تسجيل الخروج",
    "Skip to content": "تخطَّ إلى المحتوى",
    "Search pages… (Ctrl+K)": "ابحث في الصفحات… (Ctrl+K)",
    "Type to search pages…": "اكتب للبحث في الصفحات…",
    "Language": "اللغة",
    "Main navigation": "التنقل الرئيسي",

    # ---- auth (login / splash / errors) ----
    "Welcome back": "مرحباً بعودتك",
    "Sign in to your AI workshop": "سجّل الدخول إلى ورشة الذكاء الاصطناعي الخاصة بك",
    "Email address": "البريد الإلكتروني",
    "Password": "كلمة المرور",
    "Forgot password?": "نسيت كلمة المرور؟",
    "Remember me": "تذكرني",
    "Sign in": "تسجيل الدخول",
    "— or continue with —": "— أو المتابعة عبر —",
    "Google": "جوجل",
    "Apple": "آبل",
    "Demo — any valid email + 6+ char password works.": "تجريبي — أي بريد إلكتروني صالح وكلمة مرور من 6 أحرف أو أكثر يعمل.",
    "No password reset needed — any password works.": "لا حاجة لإعادة تعيين كلمة المرور — أي كلمة مرور تعمل.",
    "Social sign-in is simulated.": "تسجيل الدخول الاجتماعي محاكى.",
    "Sign in with Google is not configured yet.": "تسجيل الدخول عبر Google غير مهيأ بعد.",
    "Sign in with Apple is not configured yet.": "تسجيل الدخول عبر Apple غير مهيأ بعد.",
    "Sign in with Google failed. Please try again.": "تعذّر تسجيل الدخول عبر Google. حاول مرة أخرى.",
    "Sign in with Apple failed. Please try again.": "تعذّر تسجيل الدخول عبر Apple. حاول مرة أخرى.",
    "Sign-in session expired. Please try again.": "انتهت صلاحية جلسة تسجيل الدخول. حاول مرة أخرى.",
    "Please enter a valid email and a password of at least 6 characters.": "يرجى إدخال بريد إلكتروني صالح وكلمة مرور لا تقل عن 6 أحرف.",
    "Your AI mechanic, always in your garage.": "ميكانيكي الذكاء الاصطناعي الخاص بك، دائماً في مرآبك.",
    "Loading your garage…": "جارٍ تحميل مرآبك…",
    "Page pulled over for inspection": "الصفحة مُوقفة للتفتيش",
    "The page you're looking for doesn't exist or was moved.": "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",
    "Back to Dashboard": "العودة إلى لوحة التحكم",
    "Report a broken link": "الإبلاغ عن رابط معطّل",
    "Page not found": "الصفحة غير موجودة",
    "Engine light on — server needs a service": "إضاءة المحرك مضاءة — الخادم يحتاج إلى صيانة",
    "Something went wrong on our side. Please try again in a moment.": "حدث خطأ ما من جهتنا. يرجى المحاولة مرة أخرى بعد قليل.",
    "Retry": "إعادة المحاولة",
    "Contact support": "التواصل مع الدعم",
    "Server error": "خطأ في الخادم",

    # ---- dashboard ----
    "Here's what's happening with your garage today.": "إليك ما يحدث في مرآبك اليوم.",
    "Ask AI Assistant": "اسأل مساعد الذكاء الاصطناعي",
    "Diagnose": "تشخيص",
    "Need help with your car?": "هل تحتاج مساعدة في سيارتك؟",
    "Describe a symptom, upload a photo or a sound recording — I'll diagnose it instantly.": "صف العرَض، ارفع صورة أو تسجيلاً صوتياً — وسأشخّص المشكلة فوراً.",
    "Open AI Chat": "افتح محادثة الذكاء الاصطناعي",
    "Total diagnoses": "إجمالي التشخيصات",
    "Active tasks": "المهام النشطة",
    "Urgent alerts": "تنبيهات عاجلة",
    "Avg. cost saved": "متوسط التوفير",
    "Vehicle summary": "ملخص السيارة",
    "Edit": "تعديل",
    "km": "كم",
    "No vehicle added": "لم تتم إضافة سيارة",
    "Add your car to personalise diagnoses.": "أضف سيارتك لتخصيص التشخيصات.",
    "Add vehicle": "إضافة سيارة",
    "Recent diagnoses": "أحدث التشخيصات",
    "View all": "عرض الكل",
    "Issue": "المشكلة",
    "Severity": "الخطورة",
    "Date": "التاريخ",
    "No diagnoses yet": "لا توجد تشخيصات بعد",
    "Run your first AI diagnosis to see results here.": "شغّل أول تشخيص بالذكاء الاصطناعي لرؤية النتائج هنا.",
    "Diagnose now": "شخّص الآن",
    "Quick actions": "إجراءات سريعة",
    "Diagnose by Text": "التشخيص بالنص",
    "Diagnose by Image": "التشخيص بالصورة",
    "Diagnose by Audio": "التشخيص بالصوت",
    "Vehicle details": "تفاصيل السيارة",
    "Maintenance": "الصيانة",
    "Maintenance reminder": "تذكير الصيانة",
    "due in": "مستحق خلال",
    "Schedule service": "جدولة خدمة",
    "All caught up": "كل شيء على ما يرام",
    "No maintenance tasks due right now.": "لا توجد مهام صيانة مستحقة الآن.",
    "Add reminder": "إضافة تذكير",
    "Recent reports": "أحدث التقارير",
    "All": "الكل",
    "Reports will appear after diagnoses.": "ستظهر التقارير بعد إجراء التشخيصات.",
    "Hello, ": "مرحباً، ",

    # ---- chat ----
    "Conversations": "المحادثات",
    "New chat": "محادثة جديدة",
    "Delete": "حذف",
    "Engine shaking": "اهتزاز المحرك",
    "Brake squeal": "صوت صرير الفرامل",
    "Warning light": "ضوء تحذيري",
    "Won't start": "لا تعمل",
    "Ask your AI mechanic anything…": "اسأل ميكانيكي الذكاء الاصطناعي أي شيء…",
    "Send": "إرسال",
    "Chat": "المحادثة",
    "Clear conversation": "مسح المحادثة",
    "Conversation cleared": "تم مسح المحادثة",
    "Search conversations…": "ابحث في المحادثات…",
    "Stop generating": "إيقاف التوليد",
    "Clear this conversation? The thread stays, all messages are removed.": "مسح هذه المحادثة؟ ستبقى المحادثة وستُحذف جميع الرسائل.",
    "Chat failed": "فشلت المحادثة",
    "Response copied to clipboard.": "تم نسخ الرد إلى الحافظة.",
    "Copy failed": "فشل النسخ",
    "Downloaded": "تم التنزيل",
    "Response saved as Markdown.": "تم حفظ الرد كملف Markdown.",

    # ---- diagnose by text ----
    "Describe the symptom in your own words and let the AI mechanic work.": "صف العرَض بكلماتك ودع ميكانيكي الذكاء الاصطناعي يعمل.",
    "Describe your car problem": "صف مشكلة سيارتك",
    "Include when it happens, where the sound comes from, and any warning lights.": "اذكر متى يحدث العرَض، ومن أين يأتي الصوت، وأي أضواء تحذيرية.",
    "Quick tags": "وسوم سريعة",
    "Engine": "المحرك",
    "Brakes": "الفرامل",
    "A/C": "التكييف",
    "Battery": "البطارية",
    "Will diagnose for your ": "سيتم التشخيص لسيارتك ",
    "Add your vehicle for better results": "أضف سيارتك للحصول على نتائج أفضل",
    "Run diagnosis": "تشغيل التشخيص",
    "Your report will appear here": "سيظهر تقريرك هنا",
    "Problem, causes, urgency, cost, parts, repair steps & a downloadable PDF.": "المشكلة، الأسباب، الخطورة، التكلفة، القطع، خطوات الإصلاح وملف PDF قابل للتحميل.",

    # ---- diagnose by image ----
    "Upload a photo of the damage, part, dashboard or leak — the AI analyses it visually.": "ارفع صورة للضرر أو القطعة أو لوحة العدادات أو التسريب — سيقوم الذكاء الاصطناعي بتحليلها بصرياً.",
    "Drag & drop your image": "اسحب وأفلت صورتك هنا",
    "or ": "أو ",
    "click to browse": "انقر للاستعراض",
    "JPG, PNG or WebP · up to 10 MB": "JPG أو PNG أو WebP · حتى 10 ميجابايت",
    "Optional: add context": "اختياري: أضف توضيحاً",
    "Analyze image": "تحليل الصورة",
    "AI analysis panel": "لوحة التحليل بالذكاء الاصطناعي",
    "Detected issue, confidence score and repair recommendations.": "المشكلة المكتشفة ونسبة الثقة وتوصيات الإصلاح.",

    # ---- diagnose by audio ----
    "Record the sound your car makes — the AI transcribes it and finds the fault.": "سجّل الصوت الذي تصدره سيارتك — سيقوم الذكاء الاصطناعي بتحويله إلى نص وتحديد العطل.",
    "Upload a sound recording": "ارفع تسجيلاً صوتياً",
    "MP3, WAV, M4A, OGG or AAC · up to 15 MB": "MP3 أو WAV أو M4A أو OGG أو AAC · حتى 15 ميجابايت",
    "Optional: describe when the sound occurs": "اختياري: صف متى يحدث الصوت",
    "Transcribe & diagnose": "تحويل إلى نص وتشخيص",
    "Audio analysis panel": "لوحة التحليل الصوتي",
    "Transcribed sound, AI diagnosis and repair suggestions.": "الصوت المحوَّل إلى نص وتشخيص الذكاء الاصطناعي واقتراحات الإصلاح.",

    # ---- diagnose by video ----
    "Diagnose by Video": "التشخيص بالفيديو",
    "Video AI": "ذكاء اصطناعي للفيديو",
    "Drag & drop a short video": "اسحب وأفلت فيديو قصير هنا",
    "MP4, WebM, MOV or MKV · up to 20 MB": "MP4 أو WebM أو MOV أو MKV · حتى 20 ميجابايت",
    "Optional: describe when it happens": "اختياري: صف متى يحدث ذلك",
    "e.g. rattling noise from the engine bay when accelerating": "مثال: صوت خشخشة من حجرة المحرك عند التسارع",
    "Analyze video": "تحليل الفيديو",
    "Video analysis panel": "لوحة تحليل الفيديو",
    "Video is larger than 20 MB.": "الفيديو أكبر من 20 ميجابايت.",
    "Please upload an MP4, WebM, MOV or MKV video.": "يرجى رفع فيديو بصيغة MP4 أو WebM أو MOV أو MKV.",

    # ---- identify vehicle by photo ----
    "Identify Vehicle": "التعرف على السيارة",
    "Drag & drop a photo of the car": "اسحب وأفلت صورة السيارة هنا",
    "Identify vehicle": "تحديد السيارة",
    "Identification panel": "لوحة التعرف",
    "Detected make, model, year and confidence score.": "الماركة والطراز والسنة ونسبة الثقة المكتشفة.",
    "Body style": "نوع الهيكل",
    "Color": "اللون",
    "Notes": "ملاحظات",

    # ---- vehicle ----
    "Add your car so every diagnosis is personalised.": "أضف سيارتك ليكون كل تشخيص مخصصاً لها.",
    "Auto-detect from message": "كشف تلقائي من رسالة",
    "Vehicle details": "تفاصيل السيارة",
    "7 quick steps — or let AI detect it for you.": "7 خطوات سريعة — أو دع الذكاء الاصطناعي يكتشفها لك.",
    "What's the brand?": "ما هي الماركة؟",
    "Choose the model": "اختر الطراز",
    "Year of registration": "سنة التسجيل",
    "Fuel type": "نوع الوقود",
    "Transmission": "ناقل الحركة",
    "Current mileage": "العداد الحالي",
    "Chassis number (VIN)": "رقم الهيكل (VIN)",
    "Kilometres on the odometer": "الكيلومترات على العداد",
    "Step 1 of 7": "الخطوة 1 من 7",
    "Step 2 of 7": "الخطوة 2 من 7",
    "Step 3 of 7": "الخطوة 3 من 7",
    "Step 4 of 7": "الخطوة 4 من 7",
    "Step 5 of 7": "الخطوة 5 من 7",
    "Step 6 of 7": "الخطوة 6 من 7",
    "Step 7 of 7": "الخطوة 7 من 7",
    "17-character vehicle identification number": "رقم تعريف المركبة المكوَّن من 17 حرفاً",
    "Optional — used to enrich diagnoses.": "اختياري — يُستخدم لتحسين دقة التشخيصات.",
    "Decode with AI": "فك التشفير بالذكاء الاصطناعي",
    "Decoded: ": "تم فك التشفير: ",
    "Review the fields and save.": "راجع الحقول ثم احفظ.",
    "VIN decoded from the chassis number.": "تم فك التشفير من رقم الهيكل.",
    "Enter a valid VIN (at least 11 characters).": "أدخل رقم هيكل صالح (11 حرفاً على الأقل).",
    "Could not decode this VIN.": "تعذّر فك تشفير رقم الهيكل هذا.",
    "Type instead": "اكتب بنفسك",
    "Type your own…": "اكتب خيارك الخاص…",
    "Type the model name below.": "اكتب اسم الطراز أدناه.",
    "Back": "رجوع",
    "Next": "التالي",
    "Save vehicle": "حفظ السيارة",
    "Current vehicle": "السيارة الحالية",
    "Updated ": "تم التحديث ",
    "No vehicle saved yet. Complete the wizard to get started.": "لم يتم حفظ سيارة بعد. أكمل المعالج للبدء.",
    "Detect vehicle with AI": "كشف السيارة بالذكاء الاصطناعي",
    "Describe your car in one sentence — the AI will fill in the details.": "صف سيارتك في جملة واحدة — سيقوم الذكاء الاصطناعي بتعبئة التفاصيل.",
    "Cancel": "إلغاء",
    "Detect": "كشف",
    "Petrol": "بنزين",
    "Diesel": "ديزل",
    "Electric": "كهربائية",
    "Hybrid": "هجينة",
    "Automatic": "أوتوماتيك",
    "Manual": "يدوي",
    "CVT": "CVT",
    "Dual-Clutch": "قابض مزدوج",
    "Select a manufacturer first.": "اختر الماركة أولاً.",

    # ---- parts map ----
    "Interactive parts map": "خريطة القطع التفاعلية",
    "Inside your car": "داخل سيارتك",
    "Click any component to inspect it — name, specifications and an AI-generated report.": "انقر على أي مكوّن لفحصه — الاسم والمواصفات وتقرير بالذكاء الاصطناعي.",
    "Parts": "القطع",
    "Part report": "تقرير القطعة",
    "Generate AI report": "توليد تقرير بالذكاء الاصطناعي",
    "Loading part details…": "جارٍ تحميل تفاصيل القطعة…",
    "Generating AI report…": "جارٍ توليد تقرير الذكاء الاصطناعي…",
    "Specifications": "المواصفات",
    "Common issues": "الأعطال الشائعة",
    "Maintenance tip": "نصيحة الصيانة",
    "Lifespan": "العمر الافتراضي",
    "AI report": "تقرير الذكاء الاصطناعي",
    "Part not found.": "القطعة غير موجودة.",
    "AI unavailable — showing catalog data.": "الذكاء الاصطناعي غير متاح — عرض بيانات الدليل.",
    "Close": "إغلاق",

    # ---- digital twin ----
    "Digital Twin": "التوأم الرقمي",
    "AI vehicle analysis": "تحليل السيارة بالذكاء الاصطناعي",
    "Powered by Gemini AI": "مدعوم بتقنية جيميني للذكاء الاصطناعي",
    "Refresh AI Analysis": "تحديث التحليل بالذكاء الاصطناعي",
    "AI analysis is temporarily unavailable.": "تحليل الذكاء الاصطناعي غير متاح مؤقتاً.",
    "Try Again": "حاول مرة أخرى",
    "View Vehicle Data": "عرض بيانات السيارة",
    "Vehicle Health": "صحة السيارة",
    "AI Predictive Maintenance": "الصيانة الوقائية بالذكاء الاصطناعي",
    "Smart Vehicle Alerts": "تنبيهات السيارة الذكية",
    "AI Insights": "رؤى الذكاء الاصطناعي",
    "AI vehicle summary": "ملخص السيارة بالذكاء الاصطناعي",
    "Cost estimate": "التكلفة التقديرية",
    "AI estimate": "تقدير بالذكاء الاصطناعي",
    "Recommended inspection": "فحص موصى به",
    "Based on available vehicle data": "بناءً على بيانات السيارة المتاحة",
    "No significant issues detected from the available information.": "لا توجد مشكلات ملحوظة من المعلومات المتاحة.",
    "AI Assistant": "المساعد الذكي",
    "Ask about this vehicle": "اسأل عن هذه السيارة",
    "The assistant knows your saved vehicle and answers specifically about it.": "يعرف المساعد سيارتك المحفوظة ويجيب عنها تحديداً.",
    "Not available": "غير متوفر",
    "Tires": "الإطارات",
    "Engine Oil": "زيت المحرك",
    "Cooling System": "نظام التبريد",
    "Suspension": "نظام التعليق",
    "Electrical": "النظام الكهربائي",
    "Last analyzed: ": "آخر تحليل: ",
    "AI analysis complete.": "اكتمل التحليل بالذكاء الاصطناعي.",
    "AI is analyzing your vehicle…": "الذكاء الاصطناعي يحلل سيارتك…",
    "Checking vehicle data…": "جارٍ فحص بيانات السيارة…",
    "Analyzing components…": "جارٍ تحليل المكونات…",
    "Generating maintenance predictions…": "جارٍ توليد توقعات الصيانة…",
    "Score": "الدرجة",
    "Status": "الحالة",
    "Analysis": "التحليل",
    "Recommendation": "التوصية",
    "Severity": "الخطورة",
    "Priority": "الأولوية",
    "Normal": "طبيعي",
    "Attention": "انتباه",
    "Warning": "تحذير",
    "Critical": "حرج",
    "Low": "منخفضة",
    "Medium": "متوسطة",
    "High": "عالية",
    "Battery": "البطارية",
    "Engine": "المحرك",
    "Brakes": "الفرامل",
    "Transmission": "ناقل الحركة",
    "Estimated next maintenance": "الصيانة التالية المتوقعة",
    "AI analysis": "تحليل الذكاء الاصطناعي",
    "AI Analysis:": "تحليل الذكاء الاصطناعي:",
    "Recommendation:": "التوصية:",
    "No component analysis available.": "لا يتوفر تحليل لهذا المكوّن.",
    "Component analysis": "تحليل المكونات",

    # ---- maintenance ----
    "Track services and never miss an interval again.": "تتبّع الخدمات ولا تفوّت فترة موعد بعد الآن.",
    "New reminder": "تذكير جديد",
    "Upcoming services": "الخدمات القادمة",
    "Service history": "سجل الخدمات",
    "Add maintenance reminder": "إضافة تذكير صيانة",
    "Service title": "عنوان الخدمة",
    "Category": "الفئة",
    "Interval (km)": "الفترة (كم)",
    "Last done at (km)": "آخر تنفيذ عند (كم)",
    "Current (km)": "الحالي (كم)",
    "Notes (optional)": "ملاحظات (اختياري)",
    "Save reminder": "حفظ التذكير",
    "Electrical": "كهربائية",
    "Climate": "التكييف",
    "Exterior": "الهيكل الخارجي",
    "General": "عام",
    "of interval used": "من الفترة المستخدمة",
    "due in ": "مستحق خلال ",
    "Mark done": "وضع علامة اكتمال",
    "Add oil changes, inspections and more.": "أضف تغيير الزيت والفحوصات والمزيد.",
    "Oil": "زيت",
    "Other": "أخرى",
    "Next service": "الخدمة التالية",
    "Current": "الحالي",
    "Remaining": "المتبقي",
    "Upcoming": "قادمة",
    "Due soon": "مستحقة قريباً",
    "Overdue": "متأخرة",

    # ---- repair guide ----
    "Step-by-step guides for common DIY repairs, with tools and torque specs.": "أدلة خطوة بخطوة لإصلاحات DIY الشائعة، مع الأدوات ومواصفات العزم.",
    "Difficulty: ": "الصعوبة: ",
    "steps": "خطوات",
    "Read guide": "قراءة الدليل",
    "min": "دقيقة",
    "All guides": "كل الأدلة",
    "Difficulty ": "الصعوبة ",
    "Tools & supplies": "الأدوات واللوازم",
    "Step-by-step": "خطوة بخطوة",
    "Important": "مهم",
    "Related guides": "أدلة ذات صلة",
    "No related guides in this category.": "لا توجد أدلة ذات صلة في هذه الفئة.",
    "Not sure this is the right fix? Ask the AI mechanic.": "غير متأكد أن هذا هو الحل الصحيح؟ اسأل ميكانيكي الذكاء الاصطناعي.",
    "Open AI Chat": "افتح محادثة الذكاء الاصطناعي",
    "Print": "طباعة",

    # ---- reports ----
    "Every AI diagnosis is stored here as a full report with PDF export.": "كل تشخيص بالذكاء الاصطناعي يُحفظ هنا كتقرير كامل مع إمكانية تصدير PDF.",
    "Print this page": "طباعة هذه الصفحة",
    "Total reports": "إجمالي التقارير",
    "Urgent issues": "مشكلات عاجلة",
    "Low risk": "مخاطر منخفضة",
    "Est. total cost": "إجمالي التكلفة التقريبي",
    "Diagnosis history": "سجل التشخيصات",
    "Vehicle": "السيارة",
    "Cost": "التكلفة",
    "Actions": "إجراءات",
    "No reports yet": "لا توجد تقارير بعد",
    "Run a diagnosis and it will be saved here automatically.": "شغّل تشخيصاً وسيُحفظ هنا تلقائياً.",
    "Start diagnosing": "ابدأ التشخيص",
    "Open report": "فتح التقرير",
    "PDF": "PDF",

    # ---- diagnosis / report ----
    "Repair Result": "نتيجة الإصلاح",
    "AI diagnosis #": "تشخيص الذكاء الاصطناعي رقم ",
    "Download PDF": "تحميل PDF",
    "AI Diagnosis · ": "تشخيص الذكاء الاصطناعي · ",
    "Summary": "الملخص",
    "Confidence": "نسبة الثقة",
    "Transcribed sound": "الصوت المحوَّل إلى نص",
    "Possible causes": "الأسباب المحتملة",
    "Can I still drive?": "هل يمكنني القيادة؟",
    "Estimated cost": "التكلفة التقديرية",
    "Estimated time": "الوقت التقديري",
    "Recommended service": "مركز الخدمة الموصى به",
    "Required parts": "القطع المطلوبة",
    "Repair steps": "خطوات الإصلاح",
    "New diagnosis": "تشخيص جديد",
    "Ask follow-up in Chat": "اسأل المتابعة في المحادثة",
    "Safe to drive": "آمن للقيادة",
    "Drive carefully": "قد بحذر",
    "Service soon": "أجرِ الخدمة قريباً",
    "Stop immediately": "توقف فوراً",
    "Vehicle not set": "السيارة غير محددة",
    "AI analysis complete. See details below.": "اكتمل تحليل الذكاء الاصطناعي. انظر التفاصيل أدناه.",
    "All reports": "كل التقارير",
    "Open full report": "فتح التقرير الكامل",
    "Diagnosed image": "الصورة المُشخَّصة",
    "Recommended service centre": "مركز الخدمة الموصى به",

    # ---- settings ----
    "Tune the app to your preferences.": "اضبط التطبيق حسب تفضيلاتك.",
    "Appearance": "المظهر",
    "AI & Gemini": "الذكاء الاصطناعي وجيميني",
    "Accessibility": "إمكانية الوصول",
    "Theme": "المظهر",
    "Light": "فاتح",
    "Dark": "داكن",
    "Auto": "تلقائي",
    "Auto follows your operating system preference.": "التلقائي يتبع إعدادات نظام التشغيل الخاص بك.",
    "UI labels adapt; AI responses stay in their natural language.": "تتأقلم تسميات الواجهة؛ بينما تبقى ردود الذكاء الاصطناعي بلغتها الطبيعية.",
    "Gemini is connected": "جيميني متصل",
    "Demo mode active": "الوضع التجريبي نشط",
    "Live AI responses are enabled.": "الردود المباشرة بالذكاء الاصطناعي مفعّلة.",
    "Add your free Gemini API key to enable real AI responses.": "أضف مفتاح Gemini API المجاني لتفعيل ردود ذكاء اصطناعي حقيقية.",
    "Gemini API key": "مفتاح Gemini API",
    "Model": "الطراز",
    "Save AI settings": "حفظ إعدادات الذكاء الاصطناعي",
    "Get a free key at ": "احصل على مفتاح مجاني من ",
    "Stored in memory only.": "يُحفظ في الذاكرة فقط.",
    "Saved to the project .env file.": "يُحفظ في ملف .env الخاص بالمشروع.",
    "Test connection": "اختبار الاتصال",
    "Maintenance reminders": "تذكيرات الصيانة",
    "Alert me when services come due.": "نبّهني عندما تستحق الخدمات.",
    "Report ready": "التقرير جاهز",
    "Notify when an AI report is generated.": "أعلمني عند إنشاء تقرير بالذكاء الاصطناعي.",
    "Tips & updates": "نصائح وتحديثات",
    "Occasional driving tips and product news.": "نصائح قيادة وأخبار المنتج من وقت لآخر.",
    "Reduce motion": "تقليل الحركة",
    "Disable animations and transitions.": "تعطيل الحركات والانتقالات.",
    "High contrast": "تباين عالٍ",
    "Increase contrast of surfaces and text.": "زيادة تباين الأسطح والنصوص.",
    "Text size": "حجم النص",
    "Normal": "عادي",
    "Large": "كبير",
    "Extra large": "كبير جداً",
    "Save accessibility": "حفظ إعدادات الوصول",

    # ---- about ----
    "About ": "حول ",
    "Car Service AI turns your phone into a full automotive workshop assistant. Describe a problem in text, photograph the damage, or record the sound your car makes — the AI mechanic gives you a clear diagnosis, cost estimate and repair plan.": "تحوّل Car Service AI هاتفك إلى مساعد ورشة سيارات كامل. صف المشكلة بالنص، أو صوّر الضرر، أو سجّل الصوت الذي تصدره سيارتك — يمنحك ميكانيكي الذكاء الاصطناعي تشخيصاً واضحاً وتقدير تكلفة وخطة إصلاح.",
    "Describe the symptom and get a structured repair report in seconds.": "صف العرَض واحصل على تقرير إصلاح منظم في ثوانٍ.",
    "Upload a photo of the damage or part — AI performs visual analysis with a confidence score.": "ارفع صورة للضرر أو القطعة — يجري الذكاء الاصطناعي تحليلاً بصرياً مع نسبة ثقة.",
    "Record the noise and the AI will transcribe it and identify the fault.": "سجّل الصوت وسيقوم الذكاء الاصطناعي بتحويله إلى نص وتحديد العطل.",
    "Powered by": "مدعوم بواسطة",
    "Privacy first": "الخصوصية أولاً",
    "No database — all data lives in memory during your session.": "لا توجد قاعدة بيانات — جميع البيانات في الذاكرة أثناء جلستك.",
    "Shareable reports": "تقارير قابلة للمشاركة",
    "Every diagnosis exports to a clean PDF you can give to a mechanic.": "كل تشخيص يُصدَّر إلى PDF نظيف يمكنك تقديمه للميكانيكي.",
    "Beautiful in any light": "جميل في كل الإضاءات",
    "Full dark and light themes with a glassmorphism design system.": "مظاهر داكنة وفاتحة كاملة مع نظام تصميم زجاجي.",
    "Built for learning": "مصمم للتعلم",
    "A complete FastAPI + Bootstrap project, perfect for portfolios.": "مشروع FastAPI + Bootstrap متكامل، مثالي للمعروضات.",
    "Version": "الإصدار",
    "Contact us": "تواصل معنا",

    # ---- contact ----
    "Questions, feedback or a bug report? We'd love to hear from you.": "أسئلة أو ملاحظات أو تقرير خطأ؟ يسعدنا سماع رأيك.",
    "Your name": "اسمك",
    "Email": "البريد الإلكتروني",
    "Subject": "الموضوع",
    "Message": "الرسالة",
    "Choose a topic…": "اختر موضوعاً…",
    "General question": "سؤال عام",
    "Bug report": "تقرير خطأ",
    "Feature request": "طلب ميزة",
    "Feedback": "ملاحظات",
    "Send message": "إرسال الرسالة",
    "Prefer instant answers? The AI Chat can probably help right now.": "تفضّل إجابات فورية؟ يمكن لمحادثة الذكاء الاصطناعي مساعدتك الآن.",
    "Ask the AI mechanic": "اسأل ميكانيكي الذكاء الاصطناعي",

    # ---- misc data ----
    "General": "عام",
    "LPG/CNG": "غاز البترول المسال/الغاز الطبيعي",
    "Fuel": "الوقود",
    "Tires": "الإطارات",
    "Message is empty": "الرسالة فارغة",
    "Conversation not found": "المحادثة غير موجودة",
    "Please describe the problem in at least a few words.": "يرجى وصف المشكلة في بضع كلمات على الأقل.",
    "Image is larger than 10 MB.": "الصورة أكبر من 10 ميجابايت.",
    "Please upload a JPG, PNG or WebP image.": "يرجى رفع صورة بصيغة JPG أو PNG أو WebP.",
    "Empty file.": "الملف فارغ.",
    "Audio is larger than 15 MB.": "الملف الصوتي أكبر من 15 ميجابايت.",
    "Please upload an MP3, WAV, M4A, OGG or AAC file.": "يرجى رفع ملف بصيغة MP3 أو WAV أو M4A أو OGG أو AAC.",
    "Empty message.": "الرسالة فارغة.",
    "Could not detect a vehicle from that message. Try including the brand and model, e.g. 'Audi A4 2021'.": "تعذّر كشف السيارة من هذه الرسالة. جرّب ذكر الماركة والطراز، مثل «أودي A4 2021».",
    "Title is required.": "العنوان مطلوب.",
    "Please fill in all fields correctly.": "يرجى ملء جميع الحقول بشكل صحيح.",
    "Thanks {name}! Your message has been received.": "شكراً {name}! تم استلام رسالتك.",
    "Unsupported language": "اللغة غير مدعومة",
    "chat_greeting": "👋 أهلاً! أنا ميكانيكي الذكاء الاصطناعي. صِف أي مشكلة في سيارتك — أو ارفع صورة أو تسجيلاً صوتياً — وسأساعدك في تشخيصها.",
    "ai_unavailable": "خدمة الذكاء الاصطناعي غير متاحة. أضف مفتاح Gemini API من صفحة الإعدادات لتفعيل ميزات الذكاء الاصطناعي.",

    # ---- placeholders & print extras ----
    "of the interval used": "من الفترة المستخدمة",
    "e.g. There is a knocking sound from the front left when I turn, and the check engine light came on…": "مثال: هناك صوت طرقات من الأمام الأيسر عند الانعطاف، وأضاء ضوء فحص المحرك…",
    "e.g. front bumper after a parking accident": "مثال: المصد الأمامي بعد حادث مواقف",
    "e.g. ticking noise when the engine is warm": "مثال: صوت طقطقة عندما يكون المحرك دافئاً",
    "e.g. 62000": "مثال: 62000",
    "e.g. I drive a white Audi A4 from 2021, diesel, automatic…": "مثال: أقود سيارة أودي A4 بيضاء من 2021، ديزل، أوتوماتيك…",
    "e.g. Brake fluid flush": "مثال: تغيير سائل الفرامل",
    "Specs, torque, reminders…": "المواصفات، العزم، التذكيرات…",
    "recommended": "موصى به",
    "Diagnosis Report": "تقرير التشخيص",
    "Report ": "تقرير رقم ",
    "Vehicle: ": "السيارة: ",
    "Mode: ": "الوضع: ",
    "diagnosis": "تشخيص",
    "Summary: ": "الملخص: ",
    "Generated by ": "تم الإنشاء بواسطة ",
    "Informational guidance only — always consult a certified mechanic.": "إرشادات معلوماتية فقط — استشر دائماً ميكانيكياً معتمداً.",
    "Print / Save as PDF": "طباعة / حفظ كملف PDF",
    "Jane Doe": "جين دو",
    "you@example.com": "you@example.com",
    "Tell us what's on your mind…": "أخبرنا بما يدور في ذهنك…",

    # ---- My Garage (vehicle) ----
    "My Garage": "مرآبي",
    "AI auto-detect": "اكتشاف تلقائي بالذكاء الاصطناعي",
    "Describe your car in a sentence…": "صف سيارتك في جملة واحدة…",
    "Detecting…": "جارٍ الاكتشاف…",
    "Detected from your description.": "تم اكتشاف البيانات من وصفك.",
    "No details found — enter manually.": "لم يتم العثور على تفاصيل — أدخلها يدوياً.",
    "Detection failed.": "فشل الاكتشاف.",
    "AI unavailable — enter details manually.": "الذكاء الاصطناعي غير متاح — أدخل التفاصيل يدوياً.",
    "Manufacturer": "الصانع",
    "Year": "السنة",
    "Mileage (km)": "المسافة المقطوعة (كم)",
    "Mileage": "المسافة المقطوعة",
    "VIN / chassis (optional)": "رقم الشاصي (اختياري)",
    "VIN / chassis": "رقم الشاصي",
    "Vehicle profile": "ملف السيارة",
    "Edit vehicle": "تعديل السيارة",
    "Refresh AI analysis": "تحديث التحليل بالذكاء الاصطناعي",
    "Fill in your vehicle profile to enable the AI health check.": "أكمل ملف سيارتك لتفعيل فحص الصحة بالذكاء الاصطناعي.",
    "Digital twin · AI health check": "التوأم الرقمي · فحص الصحة بالذكاء الاصطناعي",
    "AI Car Mechanic · Smart Garage": "ميكانيكي سيارات ذكي · مرآب ذكي",
    "What's the brand?": "ما العلامة التجارية؟",
    "Choose the model": "اختر الموديل",
    "When was your car built?": "متى صُنعت سيارتك؟",
    "What does your car run on?": "ما الذي تعمل به سيارتك؟",
    "Automatic or manual?": "أوتوماتيك أم يدوي؟",
    "Confirm your vehicle details below.": "أكّد تفاصيل سيارتك أدناه.",
    "Nothing to review yet.": "لا يوجد شيء للمراجعة بعد.",
    "No AI analysis yet": "لا يوجد تحليل بالذكاء الاصطناعي بعد",
    "Run an AI health check of your vehicle profile.": "شغّل فحص صحة بالذكاء الاصطناعي لملف سيارتك.",
    "Run AI health check": "تشغيل فحص الصحة بالذكاء الاصطناعي",
    "health": "الصحة",
    "Recommendations": "التوصيات",
    "Interactive blueprint": "المخطط التفاعلي",
    "Tap a marker for details": "اضغط على النقطة لعرض التفاصيل",
    "Part details": "تفاصيل القطعة",
    "Blueprint unavailable": "المخطط غير متاح",
    "Add your vehicle first to unlock the interactive blueprint.": "أضف سيارتك أولاً لفتح المخطط التفاعلي.",
    "AI unavailable — configure an API key in Settings first.": "الذكاء الاصطناعي غير متاح — أضف مفتاح API من الإعدادات أولاً.",
    "Failed to load part details.": "فشل تحميل تفاصيل القطعة.",

    "Healthy": "سليم",
    "Select…": "اختر…",
    "Your car profile, interactive blueprint and AI health check.": "ملف سيارتك والمخطط التفاعلي وفحص الصحة بالذكاء الاصطناعي.",

    # ---- Repair Guide ----
    "DIY Workshop Manual": "دليل ورشة العمل الذاتية",
    "Step-by-step guides for the most common jobs — with tools, parts and pro tips.": "أدلة خطوة بخطوة لأكثر الأعمال شيوعاً — مع الأدوات وقطع الغيار ونصائح المحترفين.",
    "guides": "أدلة",
    "Search guides…": "ابحث في الأدلة…",
    "Open": "فتح",
    "No guides match": "لا توجد أدلة مطابقة",
    "Try a different search term or category.": "جرّب كلمة بحث أو تصنيفاً مختلفاً.",
    "Steps": "الخطوات",
    "Pro tip": "نصيحة احترافية",
    "You will need": "ماذا ستحتاج",
    "Tools": "الأدوات",
}

# ---------------------------------------------------------------------------
# JS-facing strings (rendered into window.CS_I18N)
# ---------------------------------------------------------------------------

AR_JS: dict[str, str] = {
    "Loading your garage…": "جارٍ تحميل مرآبك…",
    "Calibrating sensors…": "معايرة المستشعرات…",
    "Warming up the AI mechanic…": "تسخين ميكانيكي الذكاء الاصطناعي…",
    "Checking tire pressure…": "فحص ضغط الإطارات…",
    "Ready to help you!": "جاهز لمساعدتك!",
    "Copy response": "نسخ الرد",
    "Download response": "تحميل الرد",
    "Regenerate response": "إعادة إنشاء الرد",
    "Copied": "تم النسخ",
    "Response copied to clipboard.": "تم نسخ الرد إلى الحافظة.",
    "Copy failed": "فشل النسخ",
    "Downloaded": "تم التحميل",
    "Response saved as Markdown.": "تم حفظ الرد بصيغة Markdown.",
    "Delete this conversation?": "حذف هذه المحادثة؟",
    "Clear this conversation? The thread stays, all messages are removed.": "مسح هذه المحادثة؟ ستبقى المحادثة وستُحذف جميع الرسائل.",
    "Conversation cleared": "تم مسح المحادثة",
    "Chat failed": "فشلت المحادثة",
    "Please try again.": "يرجى المحاولة مرة أخرى.",
    "chat_greeting": "👋 أهلاً! أنا ميكانيكي الذكاء الاصطناعي. صِف أي مشكلة في سيارتك — أو ارفع صورة أو تسجيلاً صوتياً — وسأساعدك في تشخيصها.",
    "Ask the AI mechanic…": "اسأل ميكانيكي الذكاء الاصطناعي…",
    "Asking the AI mechanic…": "جارٍ سؤال ميكانيكي الذكاء الاصطناعي…",
    "Reading the image…": "جارٍ قراءة الصورة…",
    "Listening and analyzing…": "جارٍ الاستماع والتحليل…",
    "Add a description": "أضف وصفاً",
    "Describe the problem in a few words.": "صف المشكلة في بضع كلمات.",
    "Diagnosis failed": "فشل التشخيص",
    "Invalid file": "ملف غير صالح",
    "Please choose an image.": "يرجى اختيار صورة.",
    "Please choose an audio file.": "يرجى اختيار ملف صوتي.",
    "Please choose a video.": "يرجى اختيار فيديو.",
    "Watching and analyzing…": "جارٍ المشاهدة والتحليل…",
    "Analyze video": "تحليل الفيديو",
    "Body style": "نوع الهيكل",
    "Color": "اللون",
    "Notes": "ملاحظات",
    "Remove": "إزالة",
    "Analyze image": "تحليل الصورة",
    "Analysis failed": "فشل التحليل",
    "Transcribe & diagnose": "تحويل إلى نص وتشخيص",
    "AI Diagnosis · ": "تشخيص الذكاء الاصطناعي · ",
    "Confidence": "نسبة الثقة",
    "Summary": "الملخص",
    "Download PDF": "تحميل PDF",
    "Vehicle not set": "السيارة غير محددة",
    "AI analysis complete. See details below.": "اكتمل تحليل الذكاء الاصطناعي. انظر التفاصيل أدناه.",
    "Transcribed sound": "الصوت المحوَّل إلى نص",
    "Possible causes": "الأسباب المحتملة",
    "Can I still drive?": "هل يمكنني القيادة؟",
    "Estimated cost": "التكلفة التقديرية",
    "Estimated time": "الوقت التقديري",
    "Recommended service": "مركز الخدمة الموصى به",
    "Required parts": "القطع المطلوبة",
    "Repair steps": "خطوات الإصلاح",
    "All reports": "كل التقارير",
    "Open full report": "فتح التقرير الكامل",
    "Safe to drive": "آمن للقيادة",
    "Drive carefully": "قد بحذر",
    "Service soon": "أجرِ الخدمة قريباً",
    "Stop immediately": "توقف فوراً",
    "Save vehicle": "حفظ السيارة",
    "Next": "التالي",
    "Select a manufacturer first.": "اختر الماركة أولاً.",
    "Type instead": "اكتب بنفسك",
    "Type your own…": "اكتب خيارك الخاص…",
    "Type the model name below.": "اكتب اسم الطراز أدناه.",
    "Chassis number (VIN)": "رقم الهيكل (VIN)",
    "Decode with AI": "فك التشفير بالذكاء الاصطناعي",
    "Decoded: ": "تم فك التشفير: ",
    "Review the fields and save.": "راجع الحقول ثم احفظ.",
    "VIN decoded from the chassis number.": "تم فك التشفير من رقم الهيكل.",
    "Enter a valid VIN (at least 11 characters).": "أدخل رقم هيكل صالح (11 حرفاً على الأقل).",
    "Could not decode this VIN.": "تعذّر فك تشفير رقم الهيكل هذا.",
    "Interactive parts map": "خريطة القطع التفاعلية",
    "Inside your car": "داخل سيارتك",
    "Click any component to inspect it — name, specifications and an AI-generated report.": "انقر على أي مكوّن لفحصه — الاسم والمواصفات وتقرير بالذكاء الاصطناعي.",
    "Parts": "القطع",
    "Part report": "تقرير القطعة",
    "Generate AI report": "توليد تقرير بالذكاء الاصطناعي",
    "Loading part details…": "جارٍ تحميل تفاصيل القطعة…",
    "Generating AI report…": "جارٍ توليد تقرير الذكاء الاصطناعي…",
    "Specifications": "المواصفات",
    "Common issues": "الأعطال الشائعة",
    "Maintenance tip": "نصيحة الصيانة",
    "Lifespan": "العمر الافتراضي",
    "AI report": "تقرير الذكاء الاصطناعي",
    "Part not found.": "القطعة غير موجودة.",
    "AI unavailable — showing catalog data.": "الذكاء الاصطناعي غير متاح — عرض بيانات الدليل.",
    "Close": "إغلاق",
    "Selection required": "مطلوب تحديد",
    "Please pick an option to continue.": "يرجى اختيار خيار للمتابعة.",
    "Say something": "اكتب شيئاً",
    "Could not detect the vehicle.": "تعذّر كشف السيارة.",
    "Detected: ": "تم الكشف: ",
    "Continue in the wizard, review and save.": "تابع في المعالج وراجع ثم احفظ.",
    "Vehicle detected": "تم كشف السيارة",
    "Vehicle detected automatically.": "تم التعرف على السيارة تلقائياً.",
    "Check the fields and save.": "تحقق من الحقول واحفظ.",
    "Describe your car in one sentence — the AI will fill in the details.": "صف سيارتك في جملة واحدة — سيقوم الذكاء الاصطناعي بتعبئة التفاصيل.",
    "Analyzing your message…": "جارٍ تحليل رسالتك…",
    "Error": "خطأ",
    "Marked done": "تم الإكمال",
    "Great — service completed.": "رائع — اكتملت الخدمة.",
    "Delete this reminder?": "حذف هذا التذكير؟",
    "Delete this history entry?": "حذف هذا السجل؟",
    "Reminder added": "تمت إضافة التذكير",
    "Tracked in your maintenance plan.": "تم تتبعه في خطة الصيانة الخاصة بك.",
    "No maintenance reminders": "لا توجد تذكيرات صيانة",
    "Add oil changes, inspections and more.": "أضف تغيير الزيت والفحوصات والمزيد.",
    "No completed services yet.": "لا توجد خدمات مكتملة بعد.",
    "due in ": "مستحق خلال ",
    "of interval used": "من الفترة المستخدمة",
    "Oil": "زيت",
    "Other": "أخرى",
    "Next service": "الخدمة التالية",
    "Current": "الحالي",
    "Remaining": "المتبقي",
    "Upcoming": "قادمة",
    "Due soon": "مستحقة قريباً",
    "Overdue": "متأخرة",
    "Saving reminder…": "جارٍ حفظ التذكير…",
    "Unable to save maintenance reminder. Please try again.": "تعذّر حفظ تذكير الصيانة. حاول مرة أخرى.",
    "Could not update the reminder. Please try again.": "تعذّر تحديث التذكير. حاول مرة أخرى.",
    "Could not delete the reminder. Please try again.": "تعذّر حذف التذكير. حاول مرة أخرى.",
    "Could not delete this history entry. Please try again.": "تعذّر حذف هذا السجل. حاول مرة أخرى.",
    "Settings saved": "تم حفظ الإعدادات",
    "Demo mode active — add a Gemini key for live AI.": "الوضع التجريبي نشط — أضف مفتاح جيميني للذكاء الاصطناعي المباشر.",
    "Gemini is connected.": "جيميني متصل.",
    "Message sent": "تم إرسال الرسالة",
    "Could not send": "تعذّر الإرسال",
    "No password reset needed — any password works.": "لا حاجة لإعادة تعيين كلمة المرور — أي كلمة مرور تعمل.",
    "Social sign-in is simulated.": "تسجيل الدخول الاجتماعي محاكى.",
    "AI service temporarily unavailable": "خدمة الذكاء الاصطناعي غير متاحة",
    "ai_unavailable": "خدمة الذكاء الاصطناعي غير متاحة. أضف مفتاح Gemini API من صفحة الإعدادات لتفعيل ميزات الذكاء الاصطناعي.",
    "Dashboard": "لوحة التحكم",
    "AI Chat": "محادثة الذكاء الاصطناعي",
    "Demo mode": "الوضع التجريبي",
    "Diagnose by Text": "التشخيص بالنص",
    "Diagnose by Image": "التشخيص بالصورة",
    "Diagnose by Audio": "التشخيص بالصوت",
    "My Vehicle": "سيارتي",
    "Maintenance": "الصيانة",
    "Repair Guide": "دليل الإصلاح",
    "Reports": "التقارير",
    "Settings": "الإعدادات",
    "About": "حول",
    "Contact": "تواصل معنا",
    "Test connection": "اختبار الاتصال",
    "Testing connection…": "جارٍ اختبار الاتصال…",
    "Connected": "متصل",
    "Invalid API Key": "مفتاح API غير صالح",
    "API Key Missing": "مفتاح API مفقود",
    "Connection failed": "فشل الاتصال",
    "Saved": "تم الحفظ",
    "Error": "خطأ",

    # ---- digital twin ----
    "Digital Twin": "التوأم الرقمي",
    "AI vehicle analysis": "تحليل السيارة بالذكاء الاصطناعي",
    "Powered by Gemini AI": "مدعوم بتقنية جيميني للذكاء الاصطناعي",
    "Refresh AI Analysis": "تحديث التحليل بالذكاء الاصطناعي",
    "AI analysis is temporarily unavailable.": "تحليل الذكاء الاصطناعي غير متاح مؤقتاً.",
    "Try Again": "حاول مرة أخرى",
    "View Vehicle Data": "عرض بيانات السيارة",
    "Vehicle Health": "صحة السيارة",
    "AI Predictive Maintenance": "الصيانة الوقائية بالذكاء الاصطناعي",
    "Smart Vehicle Alerts": "تنبيهات السيارة الذكية",
    "AI Insights": "رؤى الذكاء الاصطناعي",
    "AI vehicle summary": "ملخص السيارة بالذكاء الاصطناعي",
    "Cost estimate": "التكلفة التقديرية",
    "AI estimate": "تقدير بالذكاء الاصطناعي",
    "Recommended inspection": "فحص موصى به",
    "Based on available vehicle data": "بناءً على بيانات السيارة المتاحة",
    "No significant issues detected from the available information.": "لا توجد مشكلات ملحوظة من المعلومات المتاحة.",
    "AI Assistant": "المساعد الذكي",
    "Ask about this vehicle": "اسأل عن هذه السيارة",
    "The assistant knows your saved vehicle and answers specifically about it.": "يعرف المساعد سيارتك المحفوظة ويجيب عنها تحديداً.",
    "Not available": "غير متوفر",
    "Tires": "الإطارات",
    "Engine Oil": "زيت المحرك",
    "Cooling System": "نظام التبريد",
    "Suspension": "نظام التعليق",
    "Electrical": "النظام الكهربائي",
    "Last analyzed: ": "آخر تحليل: ",
    "AI analysis complete.": "اكتمل التحليل بالذكاء الاصطناعي.",
    "AI is analyzing your vehicle…": "الذكاء الاصطناعي يحلل سيارتك…",
    "Checking vehicle data…": "جارٍ فحص بيانات السيارة…",
    "Analyzing components…": "جارٍ تحليل المكونات…",
    "Generating maintenance predictions…": "جارٍ توليد توقعات الصيانة…",
    "Score": "الدرجة",
    "Status": "الحالة",
    "Analysis": "التحليل",
    "Recommendation": "التوصية",
    "Severity": "الخطورة",
    "Priority": "الأولوية",
    "Normal": "طبيعي",
    "Attention": "انتباه",
    "Warning": "تحذير",
    "Critical": "حرج",
    "Low": "منخفضة",
    "Medium": "متوسطة",
    "High": "عالية",
    "Battery": "البطارية",
    "Engine": "المحرك",
    "Brakes": "الفرامل",
    "Transmission": "ناقل الحركة",
    "Estimated next maintenance": "الصيانة التالية المتوقعة",
    "AI analysis": "تحليل الذكاء الاصطناعي",
    "AI Analysis:": "تحليل الذكاء الاصطناعي:",
    "Recommendation:": "التوصية:",
    "No component analysis available.": "لا يتوفر تحليل لهذا المكوّن.",
    "Component analysis": "تحليل المكونات",

    # ---- My Garage (vehicle) JS ----
    "Select…": "اختر…",
    "Detecting…": "جارٍ الاكتشاف…",
    "Detected from your description.": "تم اكتشاف البيانات من وصفك.",
    "No details found — enter manually.": "لم يتم العثور على تفاصيل — أدخلها يدوياً.",
    "Detection failed.": "فشل الاكتشاف.",
    "AI unavailable — enter details manually.": "الذكاء الاصطناعي غير متاح — أدخل التفاصيل يدوياً.",
    "AI unavailable — configure an API key in Settings first.": "الذكاء الاصطناعي غير متاح — أضف مفتاح API من الإعدادات أولاً.",
    "Failed to load part details.": "فشل تحميل تفاصيل القطعة.",
    "Type instead": "الكتابة بدلاً من ذلك",
    "Select instead": "الاختيار من القائمة بدلاً",
    "Decode with AI": "فك التشفير بالذكاء الاصطناعي",
    "Decoded: ": "تم فك التشفير: ",
    "Enter a valid VIN (at least 11 characters).": "أدخل رقم VIN صالحاً (11 حرفاً على الأقل).",
    "Could not decode this VIN.": "تعذّر فك تشفير رقم الشاصي.",
    "Nothing to review yet.": "لا يوجد شيء للمراجعة بعد.",
    "Please pick the manufacturer to continue.": "الرجاء اختيار الصانع للمتابعة.",
    "Please enter the model to continue.": "الرجاء إدخال الموديل للمتابعة.",
    "Please pick the year of registration.": "الرجاء اختيار سنة التسجيل.",
    "Please pick a fuel type.": "الرجاء اختيار نوع الوقود.",
    "Please pick a transmission.": "الرجاء اختيار ناقل الحركة.",
    "Manufacturer": "الصانع",
    "Model": "الموديل",
    "Year": "السنة",
    "Fuel type": "نوع الوقود",
    "Transmission": "ناقل الحركة",
    "Mileage": "المسافة المقطوعة",
    "VIN / chassis": "رقم الشاصي",
    "km": "كم",
    "Back": "رجوع",
    "Next": "التالي",
    "Save vehicle": "حفظ السيارة",
    "Current mileage": "المسافة الحالية",
    "Kilometres on the odometer": "الكيلومترات على العداد",
    "17-character vehicle identification number": "رقم تعريف المركبة المكوّن من 17 حرفاً",
    "Optional — used to enrich diagnoses.": "اختياري — يُستخدم لتحسين دقة التشخيصات.",
    "Review the fields and save.": "راجع الحقول واحفظ.",
    "Confirm your vehicle details below.": "أكّد تفاصيل سيارتك أدناه.",
    "Specifications": "المواصفات",
    "Lifespan": "العمر الافتراضي",
    "Maintenance tip": "نصيحة الصيانة",
    "Common issues": "الأعطال الشائعة",
    "Generate AI report": "إنشاء تقرير بالذكاء الاصطناعي",
    "AI Car Mechanic · Smart Garage": "ميكانيكي سيارات ذكي · مرآب ذكي",
}


def tr(lang: str, key: str, **kwargs: Any) -> str:
    """Translate ``key`` for ``lang`` (English keys are their own translation)."""
    text = AR.get(key, key) if lang == "ar" else key
    if kwargs:
        try:
            return text.format(**kwargs)
        except (KeyError, IndexError):
            return text
    return text


def js_bundle(lang: str) -> dict[str, str]:
    """Full JS translation table (English source -> current language)."""
    if lang == "ar":
        return dict(AR_JS)
    # English bundle: identity mapping so CS.t() finds every key.
    return {k: k for k in AR_JS}


def chat_greeting(lang: str) -> str:
    """Localized initial assistant greeting for a new chat."""
    if lang == "ar":
        return AR_JS["chat_greeting"]
    return ("👋 Hi! I'm your AI mechanic. Describe any problem with your car — "
            "or upload an image or audio recording — and I'll help you diagnose it.")


def ai_unavailable(lang: str) -> str:
    return tr(lang, "ai_unavailable") if lang == "ar" else (
        "The AI service is unavailable. Add your Gemini API key in Settings to "
        "enable AI features.")


def urgency_label(lang: str, key: str) -> str:
    """Localized urgency labels used by report pages / PDFs."""
    labels = {
        "low": ("Safe to drive", "آمن للقيادة"),
        "medium": ("Drive carefully", "قد بحذر"),
        "high": ("Service soon", "أجرِ الخدمة قريباً"),
        "critical": ("Stop immediately", "توقف فوراً"),
    }
    en, ar = labels.get(key, labels["low"])
    return ar if lang == "ar" else en
